/* eslint-disable jsx-a11y/anchor-is-valid */
import Head from 'next/head';
import Link from 'next/link';

const Index = ():any => (
  <>
    <Head>
      <title>Workout Math</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css" />
    </Head>

    <div>
      <p>Pick your poison.</p>
      <Link href="/calculator">
        <a>Plate Calculator</a>
      </Link>
    </div>
  </>
);

export default Index;
